apiVersion: v2
name: hpc-midas
description: MIDAS data acquisition system from PSI/TRIUMF with ROOT framework and web interface
type: application
version: 0.1.0
appVersion: "1.0.0"
keywords:
  - hpc
  - midas
  - daq
  - physics
  - instrumentation
  - root
home: https://github.com/jrgochan/interviews
maintainers:
  - name: Jason Gochanour
    email: jrgochan@example.com
# Dependencies handled by deployment script
