apiVersion: apps/v1
kind: Deployment
metadata:
  name: aiml-workspace
  labels:
    app: aiml-workspace
    component: ai-ml-demo
spec:
  replicas: 1
  selector:
    matchLabels:
      app: aiml-workspace
  template:
    metadata:
      labels:
        app: aiml-workspace
    spec:
      initContainers:
      - name: workspace-init
        image: image-registry.openshift-image-registry.svc:5000/hpc-interview/hpc-aiml:latest
        imagePullPolicy: Always
        command: ["/bin/bash"]
        args:
        - -c
        - |
          echo "🚀 Initializing AI/ML workspace..."
          if [ ! -f /workspace/.initialized ]; then
            echo "📂 Copying workspace files from container seed..."
            # Copy all project files from seed (inherited from hpc-base)
            cp -r /tmp/workspace-seed/* /workspace/ 2>/dev/null || true
            # Mark as initialized
            touch /workspace/.initialized
            echo "✅ Workspace initialized successfully"
          else
            echo "✅ Workspace already initialized"
          fi
          # OpenShift will handle permissions automatically
          echo "🏁 InitContainer completed successfully"
        volumeMounts:
        - name: shared-workspace
          mountPath: /workspace
        - name: shared-data
          mountPath: /data
      containers:
      - name: aiml-container
        image: image-registry.openshift-image-registry.svc:5000/hpc-interview/hpc-aiml:latest
        imagePullPolicy: Always
        command: ["/bin/bash"]
        args: ["-c", "while true; do sleep 30; done"]
        ports:
        - containerPort: 8888
          name: jupyter
        - containerPort: 6006
          name: tensorboard
        resources:
          requests:
            memory: "1Gi"
            cpu: "1000m"
          limits:
            memory: "4Gi"
            cpu: "2000m"
        volumeMounts:
        - name: shared-workspace
          mountPath: /home/hpcuser/workspace
        - name: shared-data
          mountPath: /home/hpcuser/data
        env:
        - name: JUPYTER_ENABLE_LAB
          value: "yes"
        - name: PYTHONPATH
          value: "/home/hpcuser/workspace"
      volumes:
      - name: shared-workspace
        persistentVolumeClaim:
          claimName: hpc-shared-workspace
      - name: shared-data
        persistentVolumeClaim:
          claimName: hpc-shared-data
      securityContext:
        runAsNonRoot: true
---
apiVersion: v1
kind: Service
metadata:
  name: aiml-service
  labels:
    app: aiml-workspace
spec:
  selector:
    app: aiml-workspace
  ports:
  - name: jupyter
    port: 8888
    targetPort: 8888
  - name: tensorboard
    port: 6006
    targetPort: 6006
  type: ClusterIP
---
apiVersion: route.openshift.io/v1
kind: Route
metadata:
  name: jupyter-route
  labels:
    app: aiml-workspace
spec:
  to:
    kind: Service
    name: aiml-service
  port:
    targetPort: jupyter
  tls:
    termination: edge
---
apiVersion: route.openshift.io/v1
kind: Route
metadata:
  name: tensorboard-route
  labels:
    app: aiml-workspace
spec:
  to:
    kind: Service
    name: aiml-service
  port:
    targetPort: tensorboard
  tls:
    termination: edge
