apiVersion: apps/v1
kind: Deployment
metadata:
  name: hpc-workspace
  labels:
    app: hpc-workspace
    component: interview-demo
spec:
  replicas: 1
  selector:
    matchLabels:
      app: hpc-workspace
  template:
    metadata:
      labels:
        app: hpc-workspace
    spec:
      containers:
      - name: hpc-base
        image: image-registry.openshift-image-registry.svc:5000/hpc-interview/hpc-base:latest
        imagePullPolicy: Always
        command: ["/bin/bash"]
        args: ["-c", "while true; do sleep 30; done"]
        resources:
          requests:
            memory: "512Mi"
            cpu: "500m"
          limits:
            memory: "2Gi"
            cpu: "2000m"
        volumeMounts:
        - name: shared-data
          mountPath: /shared
        env:
        - name: WORKSPACE_TYPE
          value: "hpc-base"
      volumes:
      - name: shared-data
        emptyDir: {}
      securityContext:
        runAsNonRoot: true
---
apiVersion: v1
kind: Service
metadata:
  name: hpc-workspace-svc
  labels:
    app: hpc-workspace
spec:
  selector:
    app: hpc-workspace
  ports:
  - name: ssh
    port: 22
    targetPort: 22
  type: ClusterIP
