apiVersion: apps/v1
kind: Deployment
metadata:
  name: hpc-workspace
  labels:
    app: hpc-workspace
    component: interview-demo
spec:
  replicas: 1
  selector:
    matchLabels:
      app: hpc-workspace
  template:
    metadata:
      labels:
        app: hpc-workspace
    spec:
      initContainers:
      - name: workspace-init
        image: image-registry.openshift-image-registry.svc:5000/hpc-interview/hpc-base:latest
        imagePullPolicy: Always
        command: ["/bin/bash"]
        args:
        - -c
        - |
          echo "🚀 Initializing HPC workspace..."
          if [ ! -f /workspace/.initialized ]; then
            echo "📂 Copying workspace files from container seed..."
            # Copy all project files from seed
            cp -r /tmp/workspace-seed/* /workspace/ 2>/dev/null || true
            # Mark as initialized
            touch /workspace/.initialized
            echo "✅ Workspace initialized successfully"
          else
            echo "✅ Workspace already initialized"
          fi
          # OpenShift will handle permissions automatically
          echo "🏁 InitContainer completed successfully"
        volumeMounts:
        - name: shared-workspace
          mountPath: /workspace
        - name: shared-data
          mountPath: /data
      containers:
      - name: hpc-base
        image: image-registry.openshift-image-registry.svc:5000/hpc-interview/hpc-base:latest
        imagePullPolicy: Always
        command: ["/bin/bash"]
        args: ["-c", "while true; do sleep 30; done"]
        resources:
          requests:
            memory: "512Mi"
            cpu: "500m"
          limits:
            memory: "2Gi"
            cpu: "2000m"
        volumeMounts:
        - name: shared-workspace
          mountPath: /home/hpcuser/workspace
        - name: shared-data
          mountPath: /home/hpcuser/data
        - name: legacy-shared
          mountPath: /shared
        env:
        - name: WORKSPACE_TYPE
          value: "hpc-base"
      volumes:
      - name: shared-workspace
        persistentVolumeClaim:
          claimName: hpc-shared-workspace
      - name: shared-data
        persistentVolumeClaim:
          claimName: hpc-shared-data
      - name: legacy-shared
        emptyDir: {}
      securityContext:
        runAsNonRoot: true
---
apiVersion: v1
kind: Service
metadata:
  name: hpc-workspace-svc
  labels:
    app: hpc-workspace
spec:
  selector:
    app: hpc-workspace
  ports:
  - name: ssh
    port: 22
    targetPort: 22
  type: ClusterIP
