apiVersion: v1
kind: ConfigMap
metadata:
  name: midas-nginx-config
  namespace: hpc-interview
  labels:
    app: midas-workspace
    component: interview-demo
data:
  nginx.conf: |
    # Run nginx as non-root user (OpenShift compatible)
    user nginx;
    worker_processes auto;
    error_log /tmp/error.log warn;
    pid /tmp/nginx.pid;
    
    events {
        worker_connections 1024;
    }
    
    http {
        include       /etc/nginx/mime.types;
        default_type  application/octet-stream;
        
        # OpenShift compatible temp file locations
        client_body_temp_path /tmp/client_temp;
        proxy_temp_path /tmp/proxy_temp;
        fastcgi_temp_path /tmp/fastcgi_temp;
        uwsgi_temp_path /tmp/uwsgi_temp;
        scgi_temp_path /tmp/scgi_temp;
        
        # WebSocket upgrade handling (must be defined before use)
        map $http_upgrade $connection_upgrade {
            default upgrade;
            '' close;
        }
        
        # Logging to tmp (writable by non-root)
        access_log /tmp/access.log;
        error_log /tmp/error.log;
        
        # Gzip compression
        gzip on;
        gzip_types text/plain text/css application/json application/javascript text/xml application/xml application/xml+rss text/javascript;
        
        # Upstream to MIDAS web server (IPv6 localhost:8080 - default mhttpd)
        upstream midas_backend {
            server [::1]:8080;
        }
        
        server {
            listen 8088;
            server_name _;
            
            # Health check endpoint for readiness/liveness probes
            location /nginx-health {
                access_log off;
                return 200 "nginx healthy\n";
                add_header Content-Type text/plain;
            }
            
            # Proxy all requests to MIDAS
            location / {
                proxy_pass http://midas_backend;
                proxy_set_header Host $host;
                proxy_set_header X-Real-IP $remote_addr;
                proxy_set_header X-Forwarded-For $proxy_add_x_forwarded_for;
                proxy_set_header X-Forwarded-Proto $scheme;
                proxy_set_header X-Forwarded-Host $server_name;
                
                # Preserve Content-Type header for JSON-RPC
                proxy_set_header Content-Type $content_type;
                proxy_set_header Content-Length $content_length;
                
                # Timeout settings
                proxy_connect_timeout 30s;
                proxy_send_timeout 30s;
                proxy_read_timeout 30s;
                
                # Buffer settings
                proxy_buffering off;
                proxy_request_buffering off;
                
                # Handle WebSocket upgrades (if MIDAS uses them)
                proxy_http_version 1.1;
                proxy_set_header Upgrade $http_upgrade;
                proxy_set_header Connection $connection_upgrade;
            }
        }
    }
