apiVersion: v1
kind: PersistentVolumeClaim
metadata:
  name: {{ .Values.storage.workspace.name }}
  namespace: {{ .Values.namespace }}
  labels:
    app: {{ .Values.labels.app }}
    component: {{ .Values.labels.component }}
    {{- with .Values.additionalLabels }}
    {{- toYaml . | nindent 4 }}
    {{- end }}
  {{- with .Values.annotations }}
  annotations:
    {{- toYaml . | nindent 4 }}
  {{- end }}
spec:
  accessModes:
    - {{ .Values.storage.workspace.accessMode }}
  resources:
    requests:
      storage: {{ .Values.storage.workspace.size }}
  {{- if .Values.storage.workspace.storageClass }}
  storageClassName: {{ .Values.storage.workspace.storageClass }}
  {{- end }}
---
apiVersion: v1
kind: PersistentVolumeClaim
metadata:
  name: {{ .Values.storage.data.name }}
  namespace: {{ .Values.namespace }}
  labels:
    app: {{ .Values.labels.app }}
    component: {{ .Values.labels.component }}
    {{- with .Values.additionalLabels }}
    {{- toYaml . | nindent 4 }}
    {{- end }}
  {{- with .Values.annotations }}
  annotations:
    {{- toYaml . | nindent 4 }}
  {{- end }}
spec:
  accessModes:
    - {{ .Values.storage.data.accessMode }}
  resources:
    requests:
      storage: {{ .Values.storage.data.size }}
  {{- if .Values.storage.data.storageClass }}
  storageClassName: {{ .Values.storage.data.storageClass }}
  {{- end }}
