spack:
  specs:
  # Core compilers and toolchain
  - gcc@11.3.0
  - openmpi@4.1.4 +pmi +thread_multiple fabrics=ucx schedulers=slurm
  
  # Scientific libraries with MPI variants
  - hdf5@1.14.0 +mpi +fortran +cxx +hl +threadsafe
  - netcdf-c@4.9.2 +mpi +parallel-netcdf
  - netcdf-fortran@4.6.0 ^netcdf-c+mpi
  - parallel-netcdf@1.12.3
  
  # Math libraries
  - fftw@3.3.10 +mpi +openmp precision=float,double
  - openblas@0.3.21 threads=openmp
  - scalapack@2.2.0 ^openblas threads=openmp
  - mumps@5.5.1 +mpi +parmetis +scotch +shared
  
  # I/O and data management
  - adios2@2.8.3 +mpi +hdf5 +python +fortran
  - minio-mc  # Object storage client
  
  # Development and debugging tools  
  - cmake@3.24.0 +ownlibs
  - gdb@12.1 +python +tui
  - valgrind@3.19.0 +mpi +boost
  - intel-tbb@2021.7.0
  
  # Containers and automation
  - apptainer@1.1.3 +suid
  - charliecloud@0.30
  
  # Python ecosystem for automation/analysis
  - python@3.11.0 +optimizations +tkinter
  - py-numpy@1.23.4 ^python@3.11.0
  - py-scipy@1.9.3 ^python@3.11.0  
  - py-mpi4py@3.1.4 ^python@3.11.0
  - py-h5py@3.7.0 +mpi ^python@3.11.0
  - py-matplotlib@3.6.2 ^python@3.11.0
  - py-pandas@1.5.1 ^python@3.11.0
  - py-pytest@7.2.0 ^python@3.11.0
  
  view: false
  concretizer:
    unify: true
    reuse: true
  
  packages:
    all:
      compiler: [gcc@11.3.0]
      providers:
        mpi: [openmpi@4.1.4]
        blas: [openblas]
        lapack: [openblas]
    
    # Prefer system packages for basic tools when available  
    cmake:
      externals:
      - spec: cmake@3.20.0
        prefix: /usr
      buildable: false
      
    # Performance tuning for key packages
    openmpi:
      variants: +pmi +thread_multiple fabrics=ucx schedulers=slurm
    
    hdf5:
      variants: +mpi +fortran +cxx +hl +threadsafe
      
    fftw:
      variants: +mpi +openmp precision=float,double
      
  config:
    install_tree: $spack/opt/spack
    module_roots:
      tcl: $spack/share/spack/modules
    build_stage: $spack/var/spack/stage
    misc_cache: $spack/var/spack/cache
    source_cache: $spack/var/spack/cache/_source-cache
    
  modules:
    default:
      enable: [tcl]
      tcl:
        hash_length: 0
        naming_scheme: '{name}/{version}'
        hierarchy: [mpi]
        core_compilers: [gcc@11.3.0]
        all:
          filter:
            exclude_implicits: true
          template: |
            {% block header %}
            #%Module1.0
            ## Module for {{ spec.format('{name}/{version}') }}
            ##
            ## Generated on {{ timestamp.strftime('%Y-%m-%d') }}
            {% endblock %}
            
            {% block description %}
            module-whatis "{{ spec.format('{name}: {description}') }}"
            {% endblock %}
            
            {% block environment %}
            {{ environment_modifications }}
            {% endblock %}
