apiVersion: kustomize.config.k8s.io/v1beta1
kind: Kustomization

namespace: jupyter-dev

resources:
- configmap.yaml
- secret.yaml
- rbac.yaml
- pvc.yaml
- deployment.yaml
- service.yaml
- route.yaml

commonLabels:
  app: jupyterhub
  version: "4.0"
  managed-by: "deploy-jupyterhub-script"
