apiVersion: v1
kind: PersistentVolumeClaim
metadata:
  name: jupyterhub-db-pvc
  namespace: jupyter-dev
  labels:
    app: jupyterhub
    component: hub
spec:
  accessModes:
    - ReadWriteOnce
  resources:
    requests:
      storage: 10Gi
