apiVersion: v1
kind: ServiceAccount
metadata:
  name: jupyterhub
  namespace: jupyter-dev
  labels:
    app: jupyterhub
    component: hub
---
apiVersion: rbac.authorization.k8s.io/v1
kind: Role
metadata:
  name: jupyterhub
  namespace: jupyter-dev
  labels:
    app: jupyterhub
    component: hub
rules:
- apiGroups: [""]
  resources: ["pods", "persistentvolumeclaims", "services"]
  verbs: ["get", "watch", "list", "create", "delete"]
- apiGroups: [""]
  resources: ["events"]
  verbs: ["get", "watch", "list"]
---
apiVersion: rbac.authorization.k8s.io/v1
kind: RoleBinding
metadata:
  name: jupyterhub
  namespace: jupyter-dev
  labels:
    app: jupyterhub
    component: hub
subjects:
- kind: ServiceAccount
  name: jupyterhub
  namespace: jupyter-dev
roleRef:
  kind: Role
  name: jupyterhub
  apiGroup: rbac.authorization.k8s.io
